### ISSUE TITLE
Test environement.yml files and ChemSampler class

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/chem-sampler#10]
1.  Moler - 
```python 
cd chemsampler/tools/moler
conda env create -f environment.yml
```
Then run 
```python 
from chemsampler.samplers.moler.sampler import MolerSampler

sampler = MolerSampler()
samples = sampler.sample(n= 10)
print(samples)
```

2. Bimodal - 
```python 
python 
cd chemsampler/tools/bimodal
conda env create -f environment.yml
```

3.  Test all the samplers with different smiles_lists
```python
from chemsampler import ChemSampler
from chemsampler import example

smiles_list = example()
sampler = ChemSampler()
sampled_smiles = sampler.sample(smiles_list, Sampler= 'ChemblSampler' , num_samples=100, sim_ub=0.95, sim_lb=0.3, distribution="ramp")
print(sampled_smiles)
```

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron could you test this. samplers available : [ ChemblSampler, PubChemSampler, SmallWorldSampler, StonedSampler, BimodalSampler, MolerSampler, ]. FasmifraSampler sampler needs some installations beforehand which I'm trying to include in the script itself so that user doesn't have to it setup. SmallWorldSampler might return empty sampled smiles list. I think they made changes to their API a couple of weeks ago so Sampler is unable to fetch data properly.

**Comment by anamika-yadav99** [comment]
I could also make Sampler parameter a list of samplers. Let me know if you would want that.  By default the Sampler is set to None. So in case the user doesn't input it, it randomly selects two sampler and samples. I have included this in the readme which is being updated on branch test2.

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

Thanks for this. I have tried with the ChemblSampler but I don't understand the output:

`[['CN1CCN(c2ccc(NC(=O)c3ccc(Oc4ccccc4)cc3)cc2)CC1', 'c1ccc(-c2ccc(N3CCOCC3)cc2)cc1'], [], [], ['CN1CCC(C(=O)Nc2cccc(-c3ccc(-c4nc5ccccc5[nH]4)cc3)c2)CC1', 'CS(=O)(=O)N1CCC(C(=O)Nc2ccccc2)CC1'], [], ['COc1ccc(N2CCN(C)CC2)cc1', 'CN1CCN(c2ccc(-c3ccccc3)cc2)CC1'], [], [], ['c1ccc(-c2ccc(N3CCOCC3)cc2)cc1'], [], ['CC(C)C(=O)Nc1cnc(-c2cccnc2)nc1', 'O=C(Nc1ccc(-c2cccnc2)cc1)Nc1ccc(F)c(F)c1'], [], [], [], ['COc1ccc(Cl)c(-c2ccc(NC(=O)C(C)C)cc2)c1'], []]`

What are those empty smiles?

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron example() has 10 smiles so each list in the list is for one smile. The empty list here means no smile has been sampled in the sim_lb and sim_ub range

**Comment by GemmaTuron** [comment]
> Hi @GemmaTuron example() has 10 smiles so each list in the list is for one smile. The empty list here means no smile has been sampled in the sim_lb and sim_ub range

Thanks, very clear! We need to reflect that in the README file and prepare a more intuitive way of saving the output, see the issue I've opened #11 

I suggest creating an /src folder, where the dummy.py, sampler.py and other .py files are located (instead of the notebooks folder)

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

The moler environment creation fails with the following error:
```
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python ==3.7.*; 0.2.0 Requires-Python ==3.7.*
ERROR: Could not find a version that satisfies the requirement molecule-generation==0.1.1.dev42+gcbb3660.d20221126 (from versions: 0.3.0)
ERROR: No matching distribution found for molecule-generation==0.1.1.dev42+gcbb3660.d20221126

failed

CondaEnvException: Pip failed
```

**Comment by GemmaTuron** [comment]
The bimodal environment fails with the following error:

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement chemsampler==0.0.1 (from versions: none)
ERROR: No matching distribution found for chemsampler==0.0.1

failed

CondaEnvException: Pip failed
```

**Comment by GemmaTuron** [comment]
For the Samplers:

When I try from the test-2 branch it seems the code is not updated.
I am confused between branches, because the files on main work. Can you finish edits on the branch, merge everything into main and then we work there?

```
Traceback (most recent call last):
  File "dummy.py", line 6, in <module>
    sampled_smiles = sampler.sample(smiles_list, Sampler= 'ChemblSampler', num_samples=100, sim_ub=0.95, sim_lb=0.6, distribution="ramp")
TypeError: sample() got an unexpected keyword argument 'Sampler'
```

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron could you try again. I have merged all the branches

**Comment by GemmaTuron** [comment]
Let's keep the new discussion in #13
