### ISSUE TITLE
Chunk encoding error in Small World Sampler

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#15]
The small world sampler still gives this error:
`ChunkedEncodingError: search may be incomplete`

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron  I spent a lot of time trying t figure out why this error is showing up only to find out that it's not internal to ChemSampler or SmallWorld-api. SmallWorld server is glitchy. It doesn't finish the searches most of the time. 
It's mentioned in the comment below by owner of repo smallworld-api
https://github.com/matteoferla/Python_SmallWorld_API/issues/2#issuecomment-1364639044

**Comment by GemmaTuron** [comment]
This is due to the SmallWorld API, not related to Chem-Sampler.
We will leave as is for the moment
