### ISSUE TITLE
Fasmifra installation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#16]
A bit more of information regarding the installation of fasmifra would be good, just to know if it is installed system wide or on our conda environment only.
Why do we need to run the commands from the chem-sampler directory?
`After OPAM is installed in your system run the following commands in chem-sampler directory`

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron!
`opam init` needs to be run in chem-sampler to make sure that OPAM is initialized in chem-sampler package.  Sometimes what happens is that the path to certain packages is broken and then it has to be manually added, so to just avoid that it's better to run in chem-sampler.
