### ISSUE TITLE
Input and output files

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#17]
Input and output as csv works nicely now, thanks!
There are a couple of issues we should fix though:

1. Input file: this is currently a .csv file with only one row and each smiles is one column. We need to change this to accept a csv file with one column, having "smiles" as header, which is the most typical format to pass on a smiles list in a .csv file (see current in.csv attached)
2. Output file: I'm adding here the .csv files obtained with the different samplers. Do you think we should work to have them in individual columns @miquelduranfrigola ? I don't like that they are storing the lists of results as strings, so that can be dirty to process afterwards

[in.csv](https://github.com/ersilia-os/chem-sampler/files/10921475/in.csv)
[out_bimodal.csv](https://github.com/ersilia-os/chem-sampler/files/10921406/out_bimodal.csv)
[out_Chembl.csv](https://github.com/ersilia-os/chem-sampler/files/10921407/out_Chembl.csv)
[out_fasmifra.csv](https://github.com/ersilia-os/chem-sampler/files/10921408/out_fasmifra.csv)
[out_moler.csv](https://github.com/ersilia-os/chem-sampler/files/10921409/out_moler.csv)
[out_pubchem.csv](https://github.com/ersilia-os/chem-sampler/files/10921410/out_pubchem.csv)
[out_smallworld.csv](https://github.com/ersilia-os/chem-sampler/files/10921412/out_smallworld.csv)
[out_stoned.csv](https://github.com/ersilia-os/chem-sampler/files/10921413/out_stoned.csv)

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron I have made changes to input file. Can you give me more details on how would you prefer to have output file? Should the output file include smiles along with the sampled smiles or only sampled smiles will do?

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 
Thanks for looking tino the input file.
For the output file, my concern is that the second column is a string with a list inside, which might be cumbersome to read downstream. 
So my question was if there was a nicer way of giving the output, like one column, one smiles. 
But please do not prioritize this, and focus on the generative models

**Comment by GemmaTuron** [comment]
The input file is now a .csv with a smiles list (and header) - this is written int he readme as well, thanks @anamika-yadav99 !

For the output files, we need to work on flattening the output to single lists (instead of nested as it is now)
