### ISSUE TITLE
fpsim2 install fails

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/chem-sampler#2]
fpsim2 requires python 3.8 or higher

**Comment by GemmaTuron** [comment]
And, do we need to have all FPSIM2 code inside the repository or can we just install it in the environment?

**Comment by GemmaTuron** [comment]
I've managed to run dummy.py just by installing fpsim2 from source in a conda environment with python=3.8. I am unsure why we have the whole FPSIM2 code inside the repository

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron fpsim2 in requirements.txt was fixed by you and since we have updated the package to python 3.8 it works. So, closing this issue
