### ISSUE TITLE
Feature request: revise the subsampling parameters to obtain more smiles

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#21]
Please have a look at the example notebook to follow this.

- When I run one sampler individually, I get very few molecules, for some samplers, none (Moler, Bimodal, PubChem)
- When I run all samplers at once (except Mollib) I get around 30-50 molecules per sampler (attached output: [chemsampler_output.txt](https://github.com/ersilia-os/chem-sampler/files/11039821/chemsampler_output.txt)
- I never get to 100 as specified in the num_samples. For example, Mollib is generating 237 samples but only returning one:
```
...
Sampling from model saved at epoch 10
SAMPLING DONE for model from epoch 06 in 459.46 seconds
SAMPLING DONE for model from epoch 02 in 558.96 seconds
SAMPLING DONE for model from epoch 04 in 565.04 seconds
SAMPLING DONE for model from epoch 10 in 314.49 seconds

START NOVO ANALYSIS
sampling analysis for 10_0.7 done
sampling analysis for 02_0.7 done
sampling analysis for 04_0.7 done
sampling analysis for 08_0.7 done
sampling analysis for 06_0.7 done
NOVO ANALYSIS DONE in 0.1676 seconds
237
10it [00:00, 731.33it/s]
{'MollibSampler': ['O=C(NC(Cc1ccccc1)C(=O)NC(CO)CC(O)C(Cc1ccccc1)NC(=O)OCc1cncs1)OCc1ccccc1']}
```

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron @miquelduranfrigola  the reason why  mollib and other sampler return so few molecule is  the issue in line 
https://github.com/ersilia-os/chem-sampler/blob/6e646fc73b0a7a653f02a0093c8d80b09c012199/chemsampler/sampler.py#L196   
ref_sim is selected randomly  from values and then ref_sim is subtracted from similarity score of sampled smile.

**Comment by GemmaTuron** [comment]
This seems a bit convoluted to subsample maybe.. @miquelduranfrigola let's revise this piece of code and maybe adapt it

**Comment by GemmaTuron** [comment]
I'll close this issue as outdated
