### ISSUE TITLE
Fit moler on anitmicrobial dataset

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/chem-sampler#23]
- Fit moler on antimicrobial dataset. 
- Based on the fitting process efficiency and new compounds generated decide the next step. 
- Next step could possibly be fitting moler on different unique datasets, pre-calculating molecules using fitted model  and doing a similarity search based on user input
- The goal is to make chemsampler streamline and independent of different environment setups.

**Comment by GemmaTuron** [comment]
Moler is now incorporated as a model in the Ersilia Model Hub fitted to enamine
