### ISSUE TITLE
Git LFS pointers

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#6]
When I clone this repository, the following warning appears. @anamika-yadav99 please check what is included as git lfs and what is not

git clone https://github.com/ersilia-os/chem-sampler.git
Cloning into 'chem-sampler'...
remote: Enumerating objects: 1104, done.
remote: Total 1104 (delta 0), reused 0 (delta 0), pack-reused 1104
Receiving objects: 100% (1104/1104), 397.31 MiB | 3.28 MiB/s, done.
Resolving deltas: 100% (299/299), done.
Updating files: 100% (645/645), done.
Filtering content: 100% (149/149), 640.15 MiB | 6.52 MiB/s, done.
Encountered 16 files that should have been pointers, but weren't:
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/index.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/FPSim2.io.backends.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/FPSim2.io.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/FPSim2.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/modules.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/create_fp_db.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/gpu_sim.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/install.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/limitations.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/sim.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/sim_matrix.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/subs.rst.txt
        chemsampler/tools/fpsim2/FPSim2/docs/_sources/source/user_guide/tversky.rst.txt
        chemsampler/tools/fpsim2/FPSim2/tests/data/10mols.smi
        chemsampler/tools/fpsim2/FPSim2/tests/data/test.h5
        requirements.txt

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron, This issue has been resolved. I'm closing it 
![image](https://user-images.githubusercontent.com/54634163/222730263-4804b4ae-ed2c-4656-96e9-5edd2d2a6b6a.png)

**Comment by GemmaTuron** [comment]
yes, I just checked it as well again, thanks!
