### ISSUE TITLE
Folder organisation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#8]
Hi @anamika-yadav99,

This repository becomes very heavy because it has all the libraries inside, is there any reason for that instead of simply pip / conda installing them?
This forces us to static versions of the library, we will miss new bugfixes or improvements and have to add them manually, aside from having to clone so many libraries.

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron  We cannot do pip install the generative models because they aren't packaged. They were repositories on the github and there were also a lot of bugs and inconsistencies in the code which I had to fix before including it. But  I can look for a  work around this for sure.
